name: example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  extra_pedantic: ^4.0.0
  topg:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9 

flutter:

  uses-material-design: true
